config/routes.rb
Rails.application.routes.draw do

  resources :guides do
    collection do                       # collection => no restaurant id in
      get 'search', to: "guides#search"  # RestaurantsController#top
    end
    resources :steps, only: [:create, :destroy]
    resources :bookings do
      member do
        get 'payment'
        patch 'payment', to: 'bookings#process_payment'
        patch 'confirm', to: 'bookings#confirm'
        patch 'reject', to: 'bookings#reject'
        patch 'guide_cancel', to: 'bookings#guide_cancel'
      end
    end
  end
  resources :bookings, only: [:destroy, :payment, :show]
  resources :reviews
  resources :profiles do
    member do
      get 'guide_dashboard'
      get 'user_dashboard'
    end

  end

  devise_for :users,
    controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      registrations: "registrations"
    }
  get 'nothing', to: 'pages#nothing'
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :reservations
  has_many :bookings
  has_many :guides

  validates :role, presence: true, inclusion: { in: %w(host guest admin) }
  validates :photo, presence: true
  validates :hometown, presence: true
  validates :birthday, presence: true
  validates :aboutme, presence: true

  mount_uploader :photo, PhotoUploader


  def pending_confirmations
    fail
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: [:user_dashboard, :guide_dashboard, :index, :update, :show]
  before_action :set_profile, only: [:user_dashboard, :guide_dashboard, :index, :update, :show]
  before_action :set_bookings, only: [:user_dashboard, :guide_dashboard]
  before_action :set_guide_bookings, only: [:guide_dashboard]
  before_action :set_guides, only: [:user_dashboard, :guide_dashboard]

  def show
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(guide_params)
    @profile.user_id = current_user.id
    if @profile.save
      redirect_to @profile
    else
      render :new
    end
  end

  def edit
    @attributes = Profile.attribute_names - %w(id user_id created_at updated_at)
  end

  def guide_dashboard
  end

  def update
    if @profile.update(guide_params)
      redirect_to @profile, notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  def user_dashboard
    @profile = Profile.find(params[:id])
  end

  private

  def guide_params
    params.require(:profile).permit(:role, :user_id, :photo, :photo_cache, :hometown, :birthday, :aboutme)
  end

  def set_user
    @user = User.find(current_user.id)
  end

  def set_profile
    @profile = @user.profile
  end

  def set_bookings
    @bookings = @profile.bookings
  end

  def set_guide_bookings
    @guide_bookings = []
    @profile.guides.each do |guide|
      guide.bookings.each { |booking| @guide_bookings << booking }
    end
    @guide_bookings
  end

  def set_guides
    @guides = @profile.guides
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form_profile.html.erb
<h2>Edit profile</h2>

<%= simple_form_for (@profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :hometown %>
    <%= f.input :birthday %>
    <%= f.input :aboutme, as: :text %>
    <%= f.input :photo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Update" %>
  </div>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= link_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>

<%= link_to "Back", :back %>
<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>

app/views/profiles/_form_user.html.erb
<h2>Edit <%= resource_name.to_s.humanize %></h2>

<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email, required: true, autofocus: true %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :mobile %>
    <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
      <p>Currently waiting confirmation for: <%= resource.unconfirmed_email %></p>
    <% end %>

    <%= f.input :password, autocomplete: "off", hint: "leave it blank if you don't want to change it", required: false %>
    <%= f.input :password_confirmation, required: false %>
    <%= f.input :current_password, hint: "we need your current password to confirm your changes", required: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Update" %>
  </div>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= link_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>

<%= link_to "Back", :back %>
<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>

app/views/profiles/edit.html.erb
<%= form_for @profile do |f| %>
    <% @attributes.each do |attr| %>
       <%= f.text_field attr.to_sym %>
    <% end %>
<% end %>

app/views/profiles/guide.html.erb
<h2>
  <%= "Welcome #{@user.first_name} #{@user.last_name}" %>
</h2>

<div class="container">
  <div class="row">
    <div class="col-xs-4 col-sm-3">
      <nav class="nav-sidebar">
        <ul class="nav tabs">
          <li class="active"><a href="#tab1" data-toggle="tab">Booked tours</a></li>
          <li class=""><a href="#tab2" data-toggle="tab">My tours</a></li>
        </ul>
      </nav>
    </div>
    <!-- tab content -->
    <div class="col-xs-8 col-sm-9">
      <div class="tab-content">
        <div class="tab-pane active text-style" id="tab1">
            <div class="row">
              <%= render 'guides/cardbooking' %>
          </div>
        </div>
        <div class="tab-pane text-style" id="tab2">
          <div class="row text-center">
            <div class="col-xs-12">
              <button class='btn btn-success btn-lg'>Add another tour</button>
            </div>
          </div>
          <%= render 'guides/cards' %>
        </div>

      </div>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', root_path %>



<% content_for :js do %>
<script>

</script>
<% end %>

app/views/profiles/guide_dashboard.html.erb
<% content_for(:title) do %>
  Yalla! Guide dashboard
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 text-center">
      <h3>Guide Dashboard</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4 col-sm-3">
      <nav class="nav-sidebar">
        <ul class="nav tabs">
          <li class="active"><a href="#tab1" data-toggle="tab">Booked tours</a></li>
          <li class=""><a href="#tab2" data-toggle="tab">My tours</a></li>
        </ul>
      </nav>
    </div>
    <!-- tab content -->
    <div class="col-xs-8 col-sm-9">
      <div class="tab-content">
        <div class="tab-pane active text-style" id="tab1">
            <div class="row">
              <%= render 'guides/cardbooking' %>
          </div>
        </div>
        <div class="tab-pane text-style" id="tab2">
          <div class="row text-center">
            <div class="col-xs-12">
              <%= link_to new_guide_path do %>
                <button class='btn btn-success btn-lg'>
                  Add another tour
                </button>
              <% end %>
            </div>
          </div>
          <%= render 'guides/cards' %>
        </div>

      </div>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', root_path %>



<% content_for :js do %>
<script>

</script>
<% end %>

app/views/profiles/index.html.erb
<div class="wrapper">
  <div class="page-header">
    <h2>
      <%= "Welcome #{@user.first_name}" %>
    </h2>
    <p>How do you want to continue on the site ?</p>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <% if @guest_profile %>
          <%= link_to profile_path(@guest_profile) do %>
            <button type="button" class="btn btn-success btn-lg">
              Continue as visitor
            </button>
          <% end %>
        <% else %>
          <%= link_to new_profile_path do %>
            <button type="button" class="btn btn-info btn-lg">
              Become visitor
            </button>
          <% end %>
        <% end %>
      </div>
      <div class="col-xs-12 col-sm-6">
        <% if @host_profile %>
          <%= link_to profile_path(@host_profile) do %>
            <button type="button" class="btn btn-success btn-lg">
              Continue as guide
            </button>
          <% end %>
        <% else %>
          <%= link_to new_profile_path do %>
            <button type="button" class="btn btn-info btn-lg">
              Become guide
            </button>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<h1>Profiles#new</h1>
<p>Find me in app/views/profiles/new.html.erb</p>

<%= simple_form_for @profile do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :role, collection: ["host", "guest"], selected: "guest" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profiles/show.html.erb
<div class="container">
  <div class="row">
    <h3 class="text-center">My profile</h3>
    <div class="padded"></div>
    <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4 text-center">
        <div class="card-profile">
            <div class="card-profile-img text-center">
          <%= image_tag @profile.photo, height: 100, width: 100, crop: :fill %>
            </div>
            <div class="row">
              <div class="card-profile-name">
                <p><strong><%= @profile.user.name %></strong></p>
              </div>
              <div class="col-xs-12 col-md-6 card-profile-city">
                <p><i class="fa fa-map-marker" aria-hidden="true"></i>   <%= @profile.hometown %></p>
              </div>
              <div class="col-xs-12 col-md-6 card-profile-birth">
                <p><i class="fa fa-birthday-cake" aria-hidden="true"></i>   <%= @profile.birthday %></p>
              </div>
            </div>
            <div class="card-profile-about">
              <div class="ligne"><i class="fa fa-pencil" aria-hidden="true"></i></div>
                <p><%= @profile.aboutme %></p>
                <div class="min-padded"></div>
            </div>
        </div>
    </div>
  </div>
</div>

<div class="padded"></div>

app/views/profiles/user_dashboard.html.erb
<% content_for(:title) do %>
  Yalla! User Dashboard
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 text-center">
      <h3>Visitor Dashboard</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4 col-sm-3">
      <nav class="nav-sidebar">
        <ul class="nav tabs">
          <li class=""><a href="#tab1" data-toggle="tab">My bookings</a></li>
          <li class=""><a href="#tab4" data-toggle="tab">Edit my profile</a></li>
        </ul>
      </nav>
    </div>
    <!-- tab content -->
    <div class="col-xs-8 col-sm-9 text-center">
      <div class="tab-content">
        <div class="tab-pane active text-style" id="tab1">
          <%= render 'bookings/cards' %>
        </div>
        <div class="tab-pane text-style" id="tab4">
          <%= render 'form_profile' %>
        </div>
      </div>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', root_path %>



<% content_for :js do %>
<script>

</script>
<% end %>