config/routes.rb
Rails.application.routes.draw do

  resources :guides do
    collection do                       # collection => no restaurant id in
      get 'search', to: "guides#search"  # RestaurantsController#top
    end
    resources :steps, only: [:create, :destroy]
    resources :bookings do
      member do
        get 'payment'
        patch 'payment', to: 'bookings#process_payment'
        patch 'confirm', to: 'bookings#confirm'
        patch 'reject', to: 'bookings#reject'
        patch 'guide_cancel', to: 'bookings#guide_cancel'
      end
    end
  end
  resources :bookings, only: [:destroy, :payment, :show]
  resources :reviews
  resources :profiles do
    member do
      get 'guide_dashboard'
      get 'user_dashboard'
    end

  end

  devise_for :users,
    controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      registrations: "registrations"
    }
  get 'nothing', to: 'pages#nothing'
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :guide
  belongs_to :profile
  has_many :status_flows
  has_many :statuses, through: :status_flows
  has_many :reviews

  validates :start_date, presence: true
  validates :days, inclusion: { in: 1..10 }
  validates :guide, presence: true
  validates :profile, presence: true

  def set_status_pending_payment
    status_flow = StatusFlow.new(booking_id: self.id, status_id: Status.find_by_code(10).id)
    status_flow.save
  end

  def set_status_payment_confirmed
    status_flow = StatusFlow.new(booking_id: self.id, status_id: Status.find_by_code(15).id)
    status_flow.save
  end

  def set_status_pending_confirmation
    status_flow = StatusFlow.new(booking_id: self.id, status_id: Status.find_by_code(20).id)
    status_flow.save
    # TODO: Send email to guide
  end

  def set_status_confirmed
    status_flow = StatusFlow.new(booking_id: self.id, status_id: Status.find_by_code(25).id)
    status_flow.save
  end

  def set_status_rejected
    status_flow = StatusFlow.new(booking_id: self.id, status_id: Status.find_by_code(29).id)
    status_flow.save
  end

  def set_status_cancelled_by_guide
    status_flow = StatusFlow.new(booking_id: self.id, status_id: Status.find_by_code(49).id)
    status_flow.save
  end

  def paid?
    statuses.find_by_code(15).present?
  end

  def pending?
    statuses.find_by_code(20).present? && ! (confirmed? || rejected?)
  end

  def confirmed?
    statuses.find_by_code(25).present?
  end

  def rejected?
    statuses.find_by_code(29).present?
  end

  def cancelled?
    statuses.find_by_code(39).present? || statuses.find_by_code(49).present?
  end

  def completed?
    if cancelled?
      false
    else
      end_date < Date.today
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, except: [:index, :new, :create]
  before_action :set_guide, only: [:new, :create, :index, :process_payment]
  before_action :set_profile, only: [:new, :create, :edit]
  before_action :set_status_flow, only: [:show]
  before_action :check_status, only: [:show, :edit]

  def index
    @bookings = Booking.all
  end

  def show
    if current_user.id == @booking.guide.profile.user.id
      @role = 'owner'
    elsif current_user.id == @booking.profile.user.id
      @role = 'user'
    else
      @role = 'nothing'
    end
  end

  def new
    @booking = Booking.new
  end

  def edit
  end

  def create
    @booking = @guide.bookings.build(booking_params)
    @booking.profile_id = @profile.id
    @booking.total_price = @guide.daily_price * @booking.days
    @booking.amount_paid = 0
    @booking.end_date = @booking.start_date + @booking.days

    if @booking.save
      @booking.set_status_pending_payment
      redirect_to payment_guide_booking_path(@guide, @booking), notice: 'Booking was successfully created. Please pay!'
    else
      render :new
    end
  end

  def update
    if @booking.update(booking_params)
      redirect_to @booking, notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    redirect_to :back, notice: 'Booking was successfully destroyed.'
  end

  def payment
    @booking.amount_paid = 0 if @booking.amount_paid.nil?
  end

  def process_payment
    if payment_params[:amount_paid].to_i != @booking.total_price
      redirect_to @booking, alert: "Wrong amount, please pay again"
    else
      if @booking.update(payment_params)
        @booking.set_status_payment_confirmed
        @booking.set_status_pending_confirmation
        redirect_to guide_booking_path(@guide, @booking), notice: 'Booking paid!'
        BookingMailer.guide_new_booking(@booking).deliver_now
      else
        render :payment
      end
    end
  end

  def confirm
    @booking.set_status_confirmed
    redirect_to :back, notice: 'Booking was confirmed, thank you!'
    BookingMailer.user_booking_confirmed(@booking).deliver_now
  end

  def reject
    @booking.set_status_rejected
    redirect_to :back, alert: 'Booking was rejected!'
  end

  def guide_cancel
    @booking.set_status_cancelled_by_guide
    redirect_to :back, alert: 'Booking was cancelled, fees might apply!'
    BookingMailer.user_booking_confirmed(@booking).deliver_now
  end

  private
  def set_guide
    @guide = Guide.find(params[:guide_id])
  end

  def set_profile
    # TODO: Add check if host profile doesn't exist
    @profile = Profile.find_by(user_id: current_user.id)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_status_flow
    @status_flows = StatusFlow.where(booking_id: @booking.id).order(created_at: :desc)
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :days, :meeting_time, :total_price)
  end

  def payment_params
    params.require(:booking).permit(:amount_paid)
  end

  def check_status

  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_cards.html.erb
<% if @bookings.empty? %>
  <h2>No bookings yet!</h2>
    <%= link_to guides_path do %>
      <button type="button" class="btn btn-success btn-lg">
        Start booking now!
      </button>
    <% end %>
<% else %>


<% @bookings.each do |booking| %>
  <div class="row cardlisting">
    <div class="col-xs-12 col-md-3 text-center">
      <%= image_tag booking.guide.photo, height: 200, width: 200, crop: :fill %>
    </div>

    <div class="col-xs-12 col-md-9">
      <div class="row">
        <div class="col-xs-12 col-md-6 cardlisting-description text-left">
          <h4><%= booking.guide.title %></h4>
        </div>
        <div class="col-xs-12 col-md-6 cardlisting-category">
            <% if booking.rejected? || booking.cancelled?%>
               <p><i class="fa fa-times" aria-hidden="true" style="color: red"></i></i><%= booking.status_flows.last.status.title %></p>
            <% elsif booking.confirmed? %>
              <p><i class="fa fa-check" aria-hidden="true" style="color: green"></i><%= booking.status_flows.last.status.title %></p>
            <% else %>
              <p><%= booking.status_flows.last.status.title %></p>
            <% end %>
        </div>
          <div class="col-xs-12 col-md-12 text-left cardlisting-name">
            <p> With : <%= booking.guide.profile.user.first_name %></p>
          </div>
          <div class="col-xs-12 col-md-12 text-left">
            <p> Date : <%= "#{booking.start_date} - #{booking.end_date}" %></p>
          </div>
          <div class="col-xs-12 col-md-12 text-left">
            <p> Price : <%= booking.total_price %> €</p>
          </div>
          <div class="col-xs-12 col-md-12 text-left cardlisting-mobile">
            <p> Contact : <%= booking.guide.profile.user.mobile %></p>
          </div>
          <div class="col-xs-6 col-md-12 text-right">
            <% if !booking.paid? %>

              <%= link_to payment_guide_booking_path(booking.guide,booking) do %>

                <button type="button" class="btn btn-primary">Pay now</button>
              <% end %>
            <% end %>
            <%= link_to guide_booking_path(booking.guide, booking) do %>
              <button type="button" class="btn btn-default">See Details</button>
            <% end %>
          </div>
      </div>
    </div>
  </div>
<% end %>
<% end %>

app/views/bookings/_form.html.erb
<div>
  <%= simple_form_for [@guide, @booking], :defaults => {:required => false}, html: { :class => "form-inline" } do |f| %>
    <%= f.error_notification %>
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Your booking</h4>
          </div>
          <div class="modal-body">
            <div class="form-inputs date">
                <p><strong>
                      <%= f.input :days, label: "Book this guide for ", collection: 1..10, selected: 1, include_blanks: false, input_html: { style: 'width: 40px; padding: 5px;' } %> day(s),
                        starting on  <%= f.input :start_date, as: :string, label: false, input_html: { style: 'width: 120px;' } %>
                        at <%= f.input :meeting_time, as: :string, label: false, input_html: { value: '10:00 am', style: 'width: 80px;' } %> o'clock.
                </strong></p>
            </div>
          </div>
          <div class="modal-footer text-center">
            <%= f.button :submit, 'Book now !', class: "btn btn-success btn-lg button-submit" %>
          </div>
        </div>
      </div>
    </div>
    <!-- Button trigger modal -->
    <div class="form-actions">
        <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#myModal">Book now !</button>
    </div>
  <% end %>
</div>

app/views/bookings/_progressbar.html.erb
  <div class="wrapper-progressbar">
    <div class="row">
      <div class="col-xs-12">
        <div class="progress">
          <% if @booking.cancelled? %>
            <div class="progress-bar progress-bar-danger progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
              <span class="sr-only">100%</span>
            </div>
          <% elsif @booking.completed? %>
            <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
              <span class="sr-only">100%</span>
            </div>
          <% elsif @booking.rejected? %>
            <div class="progress-bar progress-bar-danger progress-bar-striped " role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 68%">
              <span class="sr-only">68%</span>
            </div>
          <% elsif @booking.confirmed? %>
            <div class="progress-bar progress-bar-success progress-bar-striped active " role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 68%">
              <span class="sr-only">68%</span>
            </div>
          <% elsif @booking.paid? %>
             <div class="progress-bar progress-bar-warning progress-bar-striped active " role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 42%">
                <span class="sr-only"></span>
            </div>
          <% else %>
            <div class="progress-bar progress-bar-warning progress-bar-striped active " role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 16%">
              <span class="sr-only"></span>
            </div>
          <% end %>

        </div>
      </div>
      <div class="col-xs-offset-1 col-xs-2 status-flow-card">
        <i class="fa fa-check-circle" aria-hidden="true"></i><br>
        <%= "Booking Created" %><br>
        <%= @status_flows.find{ |flow| flow.code == 10 }.created_at.strftime("%d-%b %n %H:%M") %>
      </div>
      <div class="col-xs-offset-1 col-xs-2 status-flow-card">
        <% if @booking.paid? %>
          <i class="fa fa-check-circle" aria-hidden="true"></i><br>
          <%= "Booking Paid" %><br>
          <%= @status_flows.find{ |flow| flow.code == 15 }.created_at.strftime("%d-%b %n %H:%M") %>
        <% elsif !@booking.paid? %>
          <i class="fa fa-question-circle" aria-hidden="true"></i><br>
          <%= "Pending payment...`" %><br>
        <% end %>
      </div>
      <div class="col-xs-offset-1 col-xs-2 status-flow-card">
        <% if @booking.rejected? %>
          <i class="fa fa-times-circle" aria-hidden="true"></i><br>
          <%= "Rejected by guide" %><br>
          <%= @status_flows.find{ |flow| flow.code == 29 }.created_at.strftime("%d-%b %n %H:%M") %>
        <% elsif @booking.confirmed? %>
          <i class="fa fa-check-circle" aria-hidden="true"></i><br>
          <%= "Confirmed by guide" %><br>
          <%= @status_flows.find{ |flow| flow.code == 25 }.created_at.strftime("%d-%b %n %H:%M") %>
        <% elsif @booking.paid? %>
          <i class="fa fa-question-circle" aria-hidden="true"></i><br>
          <%= "Pending confirmation...`" %><br>
        <% end %>
      </div>
      <div class="col-xs-offset-1 col-xs-2 status-flow-card">
        <% if @booking.cancelled? %>
          <i class="fa fa-times-circle" aria-hidden="true"></i><br>
          <%= "Booking Cancelled !" %><br>
          <%= @status_flows.find{ |flow| (flow.code == 39 || flow.code == 49) }.created_at.strftime("%d-%b") %>
        <% elsif @booking.completed? %>
          <i class="fa fa-check-circle" aria-hidden="true"></i><br>
          <%= "Travel Completed" %><br>
          <%= @booking.end_date.strftime("%d-%b") %>
        <% end %>
      </div>
    </div>
  </div>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

  <div class="container">
    <div class="row">
      <%= render 'cards' %>
    </div>
  </div>

app/views/bookings/new.html.erb
<h1>New booking</h1>
<p>Find me in app/views/bookings/new.html.erb</p>
<div class="container">
    <div class="col-xs-12 col-sm-12">
      <%= render 'bookings/form' %>
  </div>
</div>

<% content_for (:js) do %>
  <script>
    $('#booking_start_date').datetimepicker({
      format: 'DD MMM YYYY'
    });
    $('#booking_meeting_time').datetimepicker({
      format: 'HH:mm'
    });
  </script>
<% end %>

app/views/bookings/payment.html.erb
<h1>PAY NOW!</h1>

<h3>Please pay the total amount of the booking</h3>

<p>Amount due: <%= (@booking.total_price - @booking.amount_paid) %></p>

<%= form_for @booking, url: {action: "payment"}, html: { :class => "form-inline" } do |f| %>
  <%= f.label :amount_paid %>
  <%= f.text_field :amount_paid %>
  <%= f.submit %>
<% end %>

app/views/bookings/show.html.erb
<% content_for(:title) do %>
  Yalla! Booking id <%= @booking.id%> in <%= @booking.guide.city %>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <h2>Your booking (id: <%= @booking.id %>) - <%= @role %> view</h2>
      <p><strong><em><%= "#{@booking.guide.title} with #{@booking.guide.profile.user.name}"%></em></strong></p>
        <%= "Status: #{@status_flows.last.status.title}"%>
      </p>
    </div>
    <div class="col-xs-12 col-sm-6 text-right not-padded">
      <em>
        <h4>Booking details:</h4>
        <p>
          <%= "" + @booking.start_date.strftime("%d %B %Y") %>
          <br>
          <%= "until " + @booking.end_date.strftime("%d %B %Y") if @booking.days > 1 %>
          <br>
          Price: <strong><%= @booking.total_price %> Euros</strong></p>
      </em>
    </div>
  </div>
  <div class="min-padded"></div>

  <%= render 'progressbar' %>

  <div class="min-padded"></div>

    <div class="row">
      <% if @role == 'owner' %>
        <div class="col-xs-6">
          <h3>Your visitor details</h3>
          <p><%= "Name: #{@booking.profile.user.name}" %> </p>
          <p><%= "Mobile: #{@booking.profile.user.mobile}" %> </p>
        </div>
        <div class="col-xs-6">
          <%= link_to guide_dashboard_profile_path(current_user.profile) do %>
            <button type="button" class="btn btn-default">Back</button>
          <% end %>
        </div>
      <% elsif @role == 'user' %>
        <div class="col-xs-6">
          <h3>Your Guide details</h3>
          <p><%= "Name: #{@booking.guide.profile.user.name}" %> </p>
          <p><%= "Mobile: #{@booking.guide.profile.user.mobile}" %> </p>
        </div>
        <div class="col-xs-6 text-right bottom-align">
          <%= link_to user_dashboard_profile_path(current_user.profile) do %>
            <button type="button" class="btn btn-default">Back</button>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>