config/routes.rb
Rails.application.routes.draw do

  resources :guides do
    collection do                       # collection => no restaurant id in
      get 'search', to: "guides#search"  # RestaurantsController#top
    end
    resources :steps, only: [:create, :destroy]
    resources :bookings do
      member do
        get 'payment'
        patch 'payment', to: 'bookings#process_payment'
        patch 'confirm', to: 'bookings#confirm'
        patch 'reject', to: 'bookings#reject'
        patch 'guide_cancel', to: 'bookings#guide_cancel'
      end
    end
  end
  resources :bookings, only: [:destroy, :payment, :show]
  resources :reviews
  resources :profiles do
    member do
      get 'guide_dashboard'
      get 'user_dashboard'
    end

  end

  devise_for :users,
    controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      registrations: "registrations"
    }
  get 'nothing', to: 'pages#nothing'
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="row">
    <div class="col-md-6 col-sm-6 footer-navigation">
      <h3>Yalla</h3>
      <p class="links"><a href="#">Home</a><strong> · </strong><strong></strong><a href="#">About</a><strong> · </strong><a href="#">Contact</a></p>
      <p class="company-name">Yalla © 2016 </p>
    </div>

    <div class="clearfix visible-sm-block"></div>
    <div class="col-md-6 footer-about text-right">
      <h4>About the company</h4>
      <div class="social-icons social-links">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
          <li><a href="#"><i class="fa fa-github"></i></a></li>
        </ul>
      </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navigation-clean-button navbar-transparent <%= "navbar-fixed-top" if (controller_name == "pages" && action_name == "home") %>">
  <div class="container">
    <div class="navbar-header"><%= link_to("company name", root_path, class: "navbar-brand navbar-link") %>
      <button data-toggle="collapse" data-target="#navcol-1" class="navbar-toggle collapsed"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
    </div>

    <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="navcol-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a data-toggle="dropdown" aria-expanded="false" href="#" class="dropdown-toggle btn btn-primary" style="color:white">My profile<span class="caret"></span></a>
            <ul role="menu" class="dropdown-menu">
              <li role="presentation"><%= link_to("I'm travelling", user_dashboard_profile_path(current_user.profile))%></li>
              <li role="presentation"><%= link_to("I'm a guide", guide_dashboard_profile_path(current_user.profile))%></li>
              <li role="presentation"><%= link_to("Sign out", destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        </ul>
      </div>

    <% else %>
      <div class="collapse navbar-collapse" id="navcol-1">
        <p class="navbar-text navbar-right actions ">
          <%= link_to("sign in", new_user_session_path, class: "navbar-link login") %>
          <%= link_to("sign up", new_user_registration_path, class: "btn btn-primary action-button", role: "button") %>
        </p>
      </div>
    <% end %>
  </div>
</nav>

app/views/shared/_navbarfixed.html.erb
<nav class="navbar navbar-default navigation-clean-button navbar-fixed-top navbar-transparent">
  <div class="container">
    <div class="navbar-header"><%= link_to("company name", root_path, class: "navbar-brand navbar-link") %>
      <button data-toggle="collapse" data-target="#navcol-1" class="navbar-toggle collapsed"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
    </div>

    <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="navcol-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
          <a data-toggle="dropdown" aria-expanded="false" href="#" class="dropdown-toggle btn btn-primary" style="color:white">Mon profil<span class="caret"></span></a>
            <ul role="menu" class="dropdown-menu">
              <li role="presentation"><%= link_to("Mes informations", profiles_path)%></li>
              <li role="presentation"><a href="#">Mes réservations</a></li>
              <li role="presentation"><%= link_to("Déconnexion", destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        </ul>
    </div>

    <% else %>
      <div class="collapse navbar-collapse" id="navcol-1">
        <p class="navbar-text navbar-right actions">
          <%= link_to("sign in", new_user_session_path, class: "navbar-link login") %>
          <%= link_to("sign up", new_user_registration_path, class: "btn btn-primary action-button", role: "button") %>
        </p>
      </div>
    <% end %>
  </div>
</nav>

app/views/shared/_xxxxnavbarfixed.html.erb
<nav class="navbar navbar-default navigation-clean-button navbar-transparent navbar-fixed-top" >
  <div class="container">
    <div class="navbar-header"><%= link_to("company name", root_path, class: "navbar-brand navbar-link") %>
      <button data-toggle="collapse" data-target="#navcol-1" class="navbar-toggle collapsed"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
    </div>

    <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="navcol-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a data-toggle="dropdown" aria-expanded="false" href="#" class="dropdown-toggle btn btn-primary" style="color:white">Mon profil<span class="caret"></span></a>
            <ul role="menu" class="dropdown-menu">
              <li role="presentation"><%= link_to("Mes informations", profiles_path)%></li>
              <li role="presentation"><a href="#">Mes réservations</a></li>
              <li role="presentation"><%= link_to("Déconnexion", destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        </ul>
    </div>

    <% else %>
      <div class="collapse navbar-collapse" id="navcol-1">
        <p class="navbar-text navbar-right actions">
          <%= link_to("sign in", new_user_session_path, class: "navbar-link login") %>
          <%= link_to("sign up", new_user_registration_path, class: "btn btn-primary action-button", role: "button") %>
        </p>
      </div>
    <% end %>
  </div>
</nav>