config/routes.rb
Rails.application.routes.draw do

  resources :guides do
    collection do                       # collection => no restaurant id in
      get 'search', to: "guides#search"  # RestaurantsController#top
    end
    resources :steps, only: [:create, :destroy]
    resources :bookings do
      member do
        get 'payment'
        patch 'payment', to: 'bookings#process_payment'
        patch 'confirm', to: 'bookings#confirm'
        patch 'reject', to: 'bookings#reject'
        patch 'guide_cancel', to: 'bookings#guide_cancel'
      end
    end
  end
  resources :bookings, only: [:destroy, :payment, :show]
  resources :reviews
  resources :profiles do
    member do
      get 'guide_dashboard'
      get 'user_dashboard'
    end

  end

  devise_for :users,
    controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      registrations: "registrations"
    }
  get 'nothing', to: 'pages#nothing'
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/guide.rb
class Guide < ApplicationRecord
  belongs_to :profile
  has_many :bookings
  has_many :steps
  mount_uploader :photo, PhotoUploader

  validates :title, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :photo, presence: true
  validates :daily_price, presence: true
  validates :category, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :search]
  before_action :set_guide, only: [:show, :update, :destroy, :edit]
  before_action :set_profile, only: [:new, :create, :edit, :update, :destroy]

  def index
    @disable_footer = true
    @guides = Guide.where.not(latitude: nil, longitude: nil)
    set_hash(@guides)
  end

  def show
    @booking = Booking.new
    @owner = owner?
    @guide_coordinates = {lat: @guide.latitude, lon: @guide.longitude}

    @step = Step.new
    @step_coordinates = { lat: @step.latitude, lng: @step.longitude }
    @steps = @guide.steps
    @hash = Gmaps4rails.build_markers(@steps) do |step, marker|
      marker.lat step.latitude
      marker.lng step.longitude
      marker.infowindow render_to_string(partial: "/steps/map_box", locals: { step: step })
    end
  end

  def new
    @guide = Guide.new
  end

  def create
    @guide = Guide.new(guide_params)
    @guide.profile_id = @profile.id
    if @guide.save
      redirect_to @guide, notice: 'Guide was successfully created.'
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @guide.update(guide_params)
      redirect_to @guide, notice: 'Guide was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @guide.destroy
    redirect_to guides_path , notice: 'Guide was successfully destroyed.'
  end

  def search
    @disable_footer = true
    @guides = Guide.near(params["guide"]["address"], 20)
    set_hash(@guides)
    render :index
  end

  private

  def set_profile
    @profile = current_user.profile
  end

  def set_guide
    @guide = Guide.find(params[:id])
  end

  def set_hash(guides)
    @hash = Gmaps4rails.build_markers(@guides) do |guide, marker|
      marker.lat guide.latitude
      marker.lng guide.longitude
      marker.infowindow render_to_string(partial: "/guides/map_box", locals: { guide: guide })
    end
  end

  def guide_params
    params.require(:guide).permit(:title, :description, :address, :city,
     :photo, :photo_cash, :daily_price, :category, :profile_id)
  end

  def owner?
    !current_user.nil? && current_user.id == @guide.profile.user.id
  end

end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/views/guides/_cardbooking.html.erb
<div class="padded"></div>
<% if @guide_bookings.empty? %>
  <h3>Nobody booked your tours yet!</h3>
<% else %>
  <% @guide_bookings.each do |booking| %>
    <div class="col-xs-12">
      <div class="cardbooking">
        <div class="cardbooking-category">
          <p><%= booking.guide.title %></p>
        </div>
        <div class="cardbooking-description">
          <h3><%= "Customer: #{booking.profile.user.first_name} #{booking.profile.user.last_name}" %></h3>
          <p>
            <%= "Date: #{booking.start_date} for #{booking.days} days" %>
          </p>
        </div>
        <div class="cardbooking-thumbnail">
          <p><%= booking.status_flows.last.status.title %></p>
        </div>
        <div class="cardbooking-action">
          <% if booking.cancelled? %>
          <% elsif booking.confirmed? || booking.rejected? %>
            <%= link_to guide_cancel_guide_booking_path(booking.guide, booking), method: :patch do %>
              <button type="button" class="btn btn-danger">Cancel</button>
            <% end %>
          <% elsif booking.paid? %>
            <%= link_to confirm_guide_booking_path(booking.guide, booking), method: :patch do %>
              <button type="button" class="btn btn-success">Confirm</button>
            <% end %>
            <%= link_to reject_guide_booking_path(booking.guide, booking), method: :patch do %>
              <button type="button" class="btn btn-danger">Reject</button>
            <% end %>
          <% end %>
          <%= link_to guide_booking_path(booking.guide, booking) do %>
            <button type="button" class="btn btn-default">See Details</button>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/guides/_cards.html.erb
<% if @guides.empty? %>
  <h2>No tours yet!</h2>
  <%= link_to new_guide_path do %>
      Propose a tour in your city now!
  <% end %>
<% else %>
  <% @guides.each do |guide| %>
    <div class="col-xs-12 col-sm-6 col-lg-4">
      <div class="card-guide">
        <div>
          <%= image_tag guide.photo, height: 200, width: 200, crop: :fill, :radius=>5, gravity: :auto, :class => "card-guide-img" %>
        </div>
        <%= link_to "", guide_path(guide), {class: "card-guide-link"} %>
        <div class="card-guide-price">
          <strong><%= '€' + guide.daily_price.to_s + '/day'%></strong>
        </div>
        <div class="card-guide-desc text-left">
          <p><strong><%= guide.title %></strong><br><i><%= ' by ' + guide.profile.user.first_name %></i></p>
        </div>
        <div class="card-guide-review text-left">
          <% prng = Random.new %>
          <% rating = prng.rand(2..4) %>
          <% 5.times do |r| %>
            <i class="fa fa-star<%= "-o" if rating < r %>" aria-hidden="true"></i>
          <% end %>
          </div>
        <div class="card-guide-explore">
          <%= link_to guide_path(guide) do %>
            <button type="button" class="btn btn-success btn-sm">
              <% if !current_user.nil? && current_user.id == guide.profile.user.id %>
                Manage
              <% else %>
                Explore!
              <% end %>
            </button>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/guides/_form.html.erb
<div class="container">
  <div class="row centered-form">
    <%= simple_form_for(@guide) do |f| %>
      <% if @guide.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% @guide.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
        <div class="panel panel-default">
          <div class="form-inputs">
            <div class="panel-heading">
              <h2 class="text-center">Create your guide</h2>
            </div>

              <div class="panel-body">
                <div class="row">
                  <div class="col-xs-12 col-sm-12 col-md-12">
                    <%= f.input :title %>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                    <%= f.input :description %>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                    <%= f.input :address %>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                    <%= f.input :city %>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                    <%= f.input :daily_price %>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                    <%= f.input :category %>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                    <%= f.input :photo %>
                  </div>
                </div>

                <div class="min-padded"></div>
                <div class="form-actions text-center">
                  <%= f.button :submit %>
                  <%= link_to "Back", guides_path, {class: "btn btn-primary"} %>
                </div>
               <div class="min-padded"></div>
              </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="padded"></div>

app/views/guides/_map_box.html.erb
<div class="map_box">
  <h3><%= guide.title %></h3>
  <p><%= guide.address %></p>
  <%= link_to "Details", guide_path(guide), target: :blank, class: "btn btn-warning" %>
</div>

app/views/guides/edit.html.erb
<%= render 'form' %>

app/views/guides/index.html.erb
<div class="guides-index-wrapper">
  <div class="container guides-index heigth100 width100">

    <div class="row text-center heigth100">
      <div class="col-xs-12 col-md-7 scroll heigth100">
        <h2>Browse and choose among dozens of local guides</h2>
        <div id="locationField" class="min-padded">
          <input id="guide_address" placeholder="Update search" type="text" />
          <button id="btn-index-search-update" type="button" class="btn btn-info btn-sm">Update location</button>
        </div>
        <div class="row">
          <%= render 'cards' %>
        </div>
      </div>
      <div class="col-xs-12 col-md-5 heigth100">
        <div class="index-container-map">
          <div id="map-index"></div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="min-padded"></div>


<% content_for(:js) do %>
  <script>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map-index' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
      // console.log(handler)
      // $('#map').change(function() {
      //   console.log('change');
      // });
      $('#btn-index-search-update').click(function(){
        var input = $('#guide_address').val()
        window.location.href = '/guides/search?guide%5Baddress%5D=' + input;
      });



    });
  </script>
<% end %>

app/views/guides/new.html.erb
<%= render 'form' %>

app/views/guides/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-9 col-sm-6 col-lg-4 text-center">
      <div class="notice">
        <% if @owner %>
        <p>
          <em>You are the owner of this guide:
            <%= link_to edit_guide_path(@guide.id) do %>
            <button class="btn btn-info">click here to edit</button>
            <% end %>
          </em></p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-offset-3 col-sm-6">
      <h1 class = "text-center"><%= @guide.title %></h1>
      <h3 class = "text-right"><em><%= "by #{@guide.profile.user.name}" %></em></h3>
      <div class = "text-center">
        <% if !@owner %>
        <%= render 'bookings/form' %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row min-padded">
    <h3 class = 'text-center'>About the tour...</h3>
    <div class="guide-show-box text-center">
      <div class="min-padded"></div>
      <div class="col-xs-12 col-sm-3">
        <p><strong>Description:</strong></p>
        <p><%= @guide.description %></p>
      </div>
      <div class="col-xs-12 col-sm-3">
        <p><strong>What to expect:</strong></p>
        <p><%= @guide.category %></p>
      </div>
      <div class="col-xs-12 col-sm-3">
        <p><strong>Starting point:</strong></p>
        <p><%= @guide.address %></p>
      </div>
      <div class="col-xs-12 col-sm-3">
        <p><strong>Price:</strong></p>
        <p><%= @guide.daily_price %> €/day</p>
      </div>
    </div>
  </div>
  <div class="padded"></div>
  <div class="min-padded"></div>
  <div class = "row">
    <div class="col-xs-12 col-sm-6 quarter text-center">
      <h3>My typical tour</h3>
      <div class="min-padded"></div>
      <table class="table table-hover">
        <colgroup>
        <col>
        <col class="align-right">
      </colgroup>
      <thead>
        <tr>
          <th>Step</th>
          <th>Establishment</th>
          <% if @owner %><th>Delete?</th><% end %>
        </tr>
      </thead>

      <tbody>
       <% @guide.steps.each do |step| %>
       <tr>
        <td class="text-left"><%= step.title %></td>
        <td class="text-right"><%= step.establishment %></td>
        <% if @owner %>
        <td class="text-right">
          <%= link_to guide_step_path(@guide, step) , method: :delete, data: {confirm: "are you sure ?"} do %>
          <i class="fa fa-trash" aria-hidden="true"></i>
          <% end %>
        </td>
        <% end %>
      </tr>
      <% end %>
      </tbody>
    </table>
    </div>
    <div class="col-xs-12 col-sm-6 quarter step-map">
      <div id="steps_list">
        <% @guide.steps.each do |s| %>
          <%= render "steps/step_cards", step: s %>
        <% end %>
      </div>
        <% if @owner %>
          <%= render "steps/form", guide: @guide, step: @step %>
        <% end %>
    </div>
    <div class="col-xs-12 col-sm-6 quarter step-map">
      <div class="container-map-2">
        <div id="map" style="width: 100%; height: 500px;"></div>
      </div>
    </div>
  </div>
</div>


<% content_for(:js) do %>
  <script>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
      $('#booking_start_date').datetimepicker({
        format: 'DD MMM YYYY'
      });
      $('#booking_meeting_time').datetimepicker({
        format: 'HH:mm'
      });
    });
  </script>
<% end %>